services:
  # 1. Наше Python приложение
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    volumes:
      - ./app/src:/app/src
    depends_on:
      - database
      - rabbitmq

  # 2. Прокси-сервер (Nginx)
  web-proxy:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./web-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  # 3. Брокер сообщений (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP порт
      - "15672:15672" # Management UI порт
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    restart: on-failure

  # 4. База данных (PostgreSQL)
  database:
    image: postgres:15
    environment:
      - POSTGRES_DB=nutriguide
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret_password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
